.PHONY: down help up
.DEFAULT_GOAL := help

DNSMASQ_NAME := druidfi-dnsmasq
DNSMASQ_DOMAIN := docker.druid.fi
NETWORK_NAME := druidfi-network

down: ## Tear down the environment
	$(call colorecho, "\nTear down the environment\n")
	$(call colorecho, "\nTear down the $(DNSMASQ_NAME) and remove resolver file\n")
	@docker-compose down
	@sudo rm /etc/resolver/$(DNSMASQ_DOMAIN)

help: ## Print this help
	$(call colorecho, "\nAvailable make commands:\n")
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
	@echo ""

up: ## Launch the environment
	$(call colorecho, "\nSet $(DNSMASQ_NAME) and resolver file\n")
	@sudo sh -c "echo '$$RESOLVER_BODY' > /etc/resolver/$(DNSMASQ_DOMAIN)"
	@docker network inspect $(NETWORK_NAME) > /dev/null || docker network create $(NETWORK_NAME)
	@docker-compose up -d

define colorecho
    @tput -T xterm setaf 3
    @echo $1
    @tput -T xterm sgr0
endef

define RESOLVER_BODY
# Generated by druidfi Makefile
nameserver 127.0.0.1
port 53
endef
export RESOLVER_BODY
