#!/bin/bash

shopt -s xpg_echo

# Load env file
. .env

COMMON_RESOLV_FILE=/etc/resolv.conf
UBUNTU_RESOLV_FILE=$COMMON_RESOLV_FILE

read -r -d '' RESOLVER_BODY_DARWIN << EOM
# Generated by druidfi/stonehenge
nameserver 127.0.0.1
port 53
EOM

read -r -d '' RESOLVER_BODY_LINUX << EOM
nameserver 127.0.0.1
EOM

main () {
    if [ "$(uname)" == "Darwin" ]; then
        test -d /etc/resolver || sudo mkdir -p /etc/resolver
        RESOLVER_FILE=/etc/resolver/$DOCKER_DOMAIN
        sudo sh -c "echo '$RESOLVER_BODY_DARWIN' > /etc/resolver/$DOCKER_DOMAIN" && echo "Resolver file created"
    else
        RESOLVER_FILE=$COMMON_RESOLV_FILE

        if [  -n "$(uname -a | grep Ubuntu)" ]; then
            # Stop Ubuntu default DNS server
            #sudo service systemd-resolved stop
            echo "With Ubuntu you need to handle /etc/hosts manually..."

        elif [ -f "/etc/arch-release" ]; then

            echo "Archlinux does need extra resolver modifications..."
        fi
    fi

    exit 0
}

main
