ifeq ($(OS_ID_LIKE),darwin)
	UP_PRE_TARGETS += --create-resolver-file-mac
	POST_DOWN_ACTIONS += --remove-resolver-file-mac
	RESOLVER_FILE_EXISTS := $(shell test -f /etc/resolver/${DOCKER_DOMAIN} && echo yes || echo no)
else
	UP_POST_TARGETS += --create-resolver-file-linux
endif

define RESOLVER_BODY_DARWIN
# Generated by druidfi/stonehenge
nameserver 127.0.0.1
port 6053
endef

define RESOLVER_BODY_LINUX
# Generated by druidfi/stonehenge
nameserver 127.0.0.48
endef

export RESOLVER_BODY_DARWIN
PHONY += --create-resolver-file-mac
--create-resolver-file-mac:
ifeq ($(RESOLVER_FILE_EXISTS),no)
	$(call step,Create resolver file /etc/resolver/${DOCKER_DOMAIN}...)
	@test -d /etc/resolver || sudo mkdir -p /etc/resolver
	@sudo sh -c "printf '$$RESOLVER_BODY_DARWIN' > /etc/resolver/${DOCKER_DOMAIN}" && echo "Resolver file created"
endif

export RESOLVER_BODY_LINUX
PHONY += --create-resolver-file-linux
--create-resolver-file-linux: RESOLV_CONF := /etc/resolv.conf
--create-resolver-file-linux: RESOLV_STUB := /run/systemd/resolve/stub-resolv.conf
--create-resolver-file-linux:
#
# Resolver for Ubuntu is made in post actions so dnsmasq is available in 127.0.0.48:53
#
ifeq ($(OS_ID_LIKE),arch)
	$(call step,Modify resolver file $(RESOLV_CONF)...)
	@sudo cp $(RESOLV_CONF) $(RESOLV_CONF).default
	@sudo sh -c "printf '$$RESOLVER_BODY_LINUX' > $(RESOLV_CONF)"
else ifeq ($(OS_ID),ubuntu)
	$(call step,Create resolver file /run/systemd/resolve/resolv-stonehenge.conf...)
	@sudo sh -c "printf '$$RESOLVER_BODY_LINUX' > /run/systemd/resolve/resolv-stonehenge.conf"
	@sudo ln -nsf /run/systemd/resolve/resolv-stonehenge.conf $(RESOLV_CONF)
endif

PHONY += --remove-resolver-file-mac
--remove-resolver-file-mac:
ifeq ($(RESOLVER_FILE_EXISTS),yes)
	$(call step,Remove resolver file /etc/resolver/${DOCKER_DOMAIN}...)
	@sudo rm -f "/etc/resolver/${DOCKER_DOMAIN}" && echo "Resolver file removed" || echo "Already removed"
endif

PHONY += --remove-resolver-file-linux
--remove-resolver-file-linux: RESOLV_CONF := /etc/resolv.conf
--remove-resolver-file-linux: RESOLV_STUB := /run/systemd/resolve/stub-resolv.conf
--remove-resolver-file-linux:
ifeq ($(OS_ID_LIKE),arch)
	$(call step,Restore resolver file $(RESOLV_CONF)...)
	@sudo cp $(RESOLV_CONF).default $(RESOLV_CONF)
else ifeq ($(OS_ID),ubuntu)
	$(call step,Restore resolver symlink to $(RESOLV_STUB)...)
	@sudo ln -nsf $(RESOLV_STUB) $(RESOLV_CONF)
	@sudo rm /run/systemd/resolve/resolv-stonehenge.conf
endif
