services:

  app:
    hostname: drupal.docker.so
    container_name: drupal-example-app
    image: druidfi/drupal-test:php-8.2
    depends_on:
      - db
    environment:
      APP_ENV: prod
      DRUPAL_ROUTES: https://drupal.docker.so
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -S stonehenge:1025 -t
    labels:
      traefik.enable: "true"
      traefik.http.routers.drupal-example-app.entrypoints: https
      traefik.http.routers.drupal-example-app.rule: Host(`drupal.docker.so`)
      traefik.http.routers.drupal-example-app.tls: "true"
      traefik.http.services.drupal-example-app.loadbalancer.server.port: 8080
      traefik.docker.network: stonehenge-network
    networks:
      - default
      - stonehenge-network

  db:
    container_name: drupal-example-db
    image: druidfi/mariadb:10.11-drupal-lts

networks:
  stonehenge-network:
    external: true
