global:
  sendAnonymousUsage: false

log:
  level: "DEBUG"
#  filePath: debug.log
#  format: json

#accesslog:
#  filePath: access.log
#  bufferingSize: 100

api:
  dashboard: true
  debug: true
  insecure: false
  disabledashboardad: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/configuration"
    watch: true
