services:

  app:
    image: wordpress:latest
    container_name: "wordpress-example-app"
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.wordpress-example-app.entrypoints: https
      traefik.http.routers.wordpress-example-app.rule: Host(`wordpress.docker.so`)
      traefik.http.routers.wordpress-example-app.tls: "true"
      traefik.docker.network: stonehenge-network
    networks:
      - default
      - stonehenge-network

  db:
    image: mysql:8.0
    container_name: "wordpress-example-db"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pwordpress" ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  stonehenge-network:
    external: true
