tls:
  certificates:
    - certFile: /ssl/docker.so.crt
      keyFile: /ssl/docker.so.key
    - certFile: /ssl/traefik.me.crt
      keyFile: /ssl/traefik.me.key

http:

  routers:

    traefik:
      entryPoints: https
      rule: Host(`{{ env "TRAEFIK_HOST" }}`) && (PathPrefix(`/api`) || PathPrefix(`/`))
      service: api@internal
      tls: true

    mailpit:
      entryPoints: https
      rule: Host(`{{ env "MAILPIT_HOST" }}`)
      service: mailpit@file
      tls: true

    catchall:
      entryPoints: https
      rule: HostRegexp(`{host:.+}`)
      service: errors@file
      tls: true
      priority: 1

  services:

    traefik:
      loadBalancer:
        servers:
          - url: "http://stonehenge:8080"

    mailpit:
      loadBalancer:
        servers:
          - url: "http://stonehenge:8025"

    errors:
      loadBalancer:
        servers:
          - url: "http://stonehenge:8181"

  middlewares:

    error-page:
      errors:
        status:
          - "400-599"
        service: errors@file
        query: "/usr/share/nginx/html/index.html"
