server {
    server_name typo3.docker.so;

    index index.php;

    root /app/public;

    # Deny access to sensitive paths
    location ~* /(?:\.git|composer\.(json|lock)|vendor/.*\.php) {
        deny all;
    }

    include includes/cache.conf;
    include includes/php.conf;
}
