#!/bin/bash

#shopt -s xpg_echo

get_distribution () {
  if [[ "$(uname)" == "Darwin" ]]; then
    echo "darwin"
  elif [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release && echo "${ID}"
  else
    echo "linux"
  fi
}

get_ubuntu_version () {
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release && echo "${VERSION_ID}"
  else
    echo "no-ubuntu"
  fi
}

DISTRO=$(get_distribution)

# Load env file
# shellcheck disable=SC1091
. .env

read -r -d '' RESOLVER_BODY_DARWIN << EOM
# Generated by druidfi/stonehenge
nameserver 127.0.0.1
port 6053
EOM

read -r -d '' RESOLVER_BODY_LINUX << EOM
# Generated by druidfi/stonehenge
nameserver 127.0.0.48
EOM

install_resolver () {
  if [[ "$DISTRO" == "darwin" ]]; then
    test -d /etc/resolver || sudo mkdir -p /etc/resolver
    sudo sh -c "echo '$RESOLVER_BODY_DARWIN' > /etc/resolver/$DOCKER_DOMAIN" && echo "Resolver file created"
    exit 0
  fi

  if [[ "$DISTRO" == "ubuntu" ]]; then
    #echo "$DISTRO $VERSION does not need extra resolver modifications..."
    exit 0
  elif [[ -f "/etc/resolv.conf" ]]; then
    ORIGINAL=$(cat /etc/resolv.conf)
    # Backup original resolv.conf, add our local nameserver as first.
    sudo cp /etc/resolv.conf /etc/resolv.conf.default

    if grep -q "druidfi/stonehenge" /etc/resolv.conf; then
      sudo sh -c "printf '$RESOLVER_BODY_LINUX\n$ORIGINAL' > /etc/resolv.conf"
    fi
    exit 0
  fi

  echo "Unknown distribution. You might need to handle name resolver settings manually."
  exit 0
}

post_actions() {
  if [[ "$DISTRO" == "ubuntu" ]]; then
    VERSION=$(get_ubuntu_version)

    if [[ "$VERSION" == "18.04" ]]; then
      echo "Ubuntu $VERSION needs some post actions..."
      sudo mv /etc/resolv.conf /etc/resolv.conf.bak
      sudo sh -c "printf '$RESOLVER_BODY_LINUX\n$ORIGINAL' > /etc/resolv.conf"
      sudo echo "DNSStubListener=no" > /etc/systemd/resolved.conf
      sudo systemctl daemon-reload
      sudo systemctl restart systemd-resolved.service
    else
      echo "$DISTRO $VERSION does not need extra resolver modifications..."
    fi

    exit 0
  fi
}

remove_resolver() {
  if [[ "$DISTRO" == "darwin" ]]; then
    sudo rm -f "/etc/resolver/${DOCKER_DOMAIN}" && echo "Resolver file removed" || echo "Already removed"
  else
    if [[ -f "/etc/resolv.conf.default" ]]; then
      # Remove our resolv.conf and replace with old.
      sudo rm /etc/resolv.conf && sudo mv /etc/resolv.conf.default /etc/resolv.conf
    fi
  fi
}
