UP_TARGETS := --up-title mkcert-install certs --up-pre-actions --up-create-network --up-create-volume --up addkey --up-post-actions

ifeq ($(OS_ID_LIKE),darwin)
RESOLVER_FILE_EXISTS := $(shell test -f /etc/resolver/${DOCKER_DOMAIN} && echo yes || echo no)
endif

define RESOLVER_BODY_DARWIN
# Generated by druidfi/stonehenge
nameserver 127.0.0.1
port 6053
endef

define RESOLVER_BODY_LINUX
# Generated by druidfi/stonehenge
nameserver 127.0.0.48
endef

PHONY += up
up: $(UP_TARGETS) ## Launch Stonehenge

PHONY += --up-title
--up-title:
	$(call step,\nStart Stonehenge on $(OS))

export RESOLVER_BODY_DARWIN
PHONY += --up-pre-actions
--up-pre-actions:
ifeq ($(OS_ID_LIKE),darwin)
	$(call step,Create resolver file /etc/resolver/${DOCKER_DOMAIN}...)
	@test -d /etc/resolver || sudo mkdir -p /etc/resolver
ifeq ($(RESOLVER_FILE_EXISTS),no)
	@sudo sh -c "printf '$$RESOLVER_BODY_DARWIN' > /etc/resolver/${DOCKER_DOMAIN}" && echo "Resolver file created"
else
	@printf "Resolver file already exists\n"
endif
endif

PHONY += --up-create-network
--up-create-network:
	$(call step,Create network ${NETWORK_NAME}...)
	@docker network inspect ${NETWORK_NAME} > /dev/null || \
		docker network create ${NETWORK_NAME} && echo "Network created"

PHONY += --up-create-volume
--up-create-volume:
	$(call step,Create volume ${SSH_VOLUME_NAME}...)
	@docker volume inspect ${SSH_VOLUME_NAME} > /dev/null || \
		docker volume create ${SSH_VOLUME_NAME} && echo "SSH volume created"

PHONY += --up
--up:
	$(call step,Start the containers...)
	@${DOCKER_COMPOSE_CMD} up -d --force-recreate --remove-orphans

export RESOLVER_BODY_LINUX
PHONY += --up-post-actions
--up-post-actions: RESOLV_CONF := /etc/resolv.conf
--up-post-actions: RESOLV_STUB := /run/systemd/resolve/stub-resolv.conf
--up-post-actions:
#
# Resolver for Ubuntu is made in post actions so dnsmasq is available in 127.0.0.48:53
#
ifeq ($(OS_ID_LIKE),arch)
	$(call step,Modify resolver file $(RESOLV_CONF)...)
	@sudo cp $(RESOLV_CONF) $(RESOLV_CONF).default
	@sudo sh -c "printf '$$RESOLVER_BODY_LINUX' > $(RESOLV_CONF)"
else ifeq ($(OS_ID),ubuntu)
	$(call step,Create resolver file /run/systemd/resolve/resolv-stonehenge.conf...)
	@sudo sh -c "printf '$$RESOLVER_BODY_LINUX' > /run/systemd/resolve/resolv-stonehenge.conf"
	@sudo ln -nsf /run/systemd/resolve/resolv-stonehenge.conf $(RESOLV_CONF)
endif
	$(call success,SUCCESS! Open https://portainer.${DOCKER_DOMAIN} ...)
