services:

  app:
    image: klakegg/hugo:latest
    container_name: hugo-example-hugo
    command: server --appendPort=false --baseUrl=hugo.docker.so -D
    volumes:
      - ./site:/src
    ports:
      - 1313:1313
    restart: always
    environment:
      HUGO_ENV: DEV
    labels:
      traefik.enable: "true"
      traefik.http.routers.ghost-example-app.entrypoints: https
      traefik.http.routers.ghost-example-app.rule: Host(`hugo.docker.so`)
      traefik.http.routers.ghost-example-app.tls: "true"
      traefik.http.services.ghost-example-app.loadbalancer.server.port: 1313
      traefik.docker.network: stonehenge-network
    networks:
      - default
      - stonehenge-network

networks:
  stonehenge-network:
    external: true
